require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - lib/uri/idna/data/uts46.rb

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/uri-idna.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
