# frozen_string_literal: true

# This file is automatically generated by rake idna:generate
# Unicode version 15.1.0

module URI
  module IDNA
    SCRIPTS = {
      "Greek" => "["\
        "\u0370-\u0373"\
        "\u0375-\u0377"\
        "\u037A-\u037D"\
        "\u037F"\
        "\u0384"\
        "\u0386"\
        "\u0388-\u038A"\
        "\u038C"\
        "\u038E-\u03A1"\
        "\u03A3-\u03E1"\
        "\u03F0-\u03FF"\
        "\u1D26-\u1D2A"\
        "\u1D5D-\u1D61"\
        "\u1D66-\u1D6A"\
        "\u1DBF"\
        "\u1F00-\u1F15"\
        "\u1F18-\u1F1D"\
        "\u1F20-\u1F45"\
        "\u1F48-\u1F4D"\
        "\u1F50-\u1F57"\
        "\u1F59"\
        "\u1F5B"\
        "\u1F5D"\
        "\u1F5F-\u1F7D"\
        "\u1F80-\u1FB4"\
        "\u1FB6-\u1FC4"\
        "\u1FC6-\u1FD3"\
        "\u1FD6-\u1FDB"\
        "\u1FDD-\u1FEF"\
        "\u1FF2-\u1FF4"\
        "\u1FF6-\u1FFE"\
        "\u2126"\
        "\uAB65"\
        "\u{10140}-\u{1018E}"\
        "\u{101A0}"\
        "\u{1D200}-\u{1D245}"\
        "]",
      "Han" => "["\
        "\u2E80-\u2E99"\
        "\u2E9B-\u2EF3"\
        "\u2F00-\u2FD5"\
        "\u3005"\
        "\u3007"\
        "\u3021-\u3029"\
        "\u3038-\u303B"\
        "\u3400-\u4DBF"\
        "\u4E00-\u9FFF"\
        "\uF900-\uFA6D"\
        "\uFA70-\uFAD9"\
        "\u{16FE2}\u{16FE3}"\
        "\u{16FF0}\u{16FF1}"\
        "\u{20000}-\u{2A6DF}"\
        "\u{2A700}-\u{2B739}"\
        "\u{2B740}-\u{2B81D}"\
        "\u{2B820}-\u{2CEA1}"\
        "\u{2CEB0}-\u{2EBE0}"\
        "\u{2EBF0}-\u{2EE5D}"\
        "\u{2F800}-\u{2FA1D}"\
        "\u{30000}-\u{3134A}"\
        "\u{31350}-\u{323AF}"\
        "]",
      "Hebrew" => "["\
        "\u0591-\u05C7"\
        "\u05D0-\u05EA"\
        "\u05EF-\u05F4"\
        "\uFB1D-\uFB36"\
        "\uFB38-\uFB3C"\
        "\uFB3E"\
        "\uFB40\uFB41"\
        "\uFB43\uFB44"\
        "\uFB46-\uFB4F"\
        "]",
      "Hiragana" => "["\
        "\u3041-\u3096"\
        "\u309D-\u309F"\
        "\u{1B001}-\u{1B11F}"\
        "\u{1B132}"\
        "\u{1B150}-\u{1B152}"\
        "\u{1F200}"\
        "]",
      "Katakana" => "["\
        "\u30A1-\u30FA"\
        "\u30FD-\u30FF"\
        "\u31F0-\u31FF"\
        "\u32D0-\u32FE"\
        "\u3300-\u3357"\
        "\uFF66-\uFF6F"\
        "\uFF71-\uFF9D"\
        "\u{1AFF0}-\u{1AFF3}"\
        "\u{1AFF5}-\u{1AFFB}"\
        "\u{1AFFD}\u{1AFFE}"\
        "\u{1B000}"\
        "\u{1B120}-\u{1B122}"\
        "\u{1B155}"\
        "\u{1B164}-\u{1B167}"\
        "]",
    }.freeze
  end
end
