# frozen_string_literal: true

# This file is automatically generated by bin/generate
# Unicode version 15.1.0

module URI
  module IDNA
    VIRAMA_COMBINING_CLASSES = "["\
      "\u094D"\
      "\u09CD"\
      "\u0A4D"\
      "\u0ACD"\
      "\u0B4D"\
      "\u0BCD"\
      "\u0C4D"\
      "\u0CCD"\
      "\u0D3B\u0D3C"\
      "\u0D4D"\
      "\u0DCA"\
      "\u0E3A"\
      "\u0EBA"\
      "\u0F84"\
      "\u1039\u103A"\
      "\u1714\u1715"\
      "\u1734"\
      "\u17D2"\
      "\u1A60"\
      "\u1B44"\
      "\u1BAA\u1BAB"\
      "\u1BF2\u1BF3"\
      "\u2D7F"\
      "\uA806"\
      "\uA82C"\
      "\uA8C4"\
      "\uA953"\
      "\uA9C0"\
      "\uAAF6"\
      "\uABED"\
      "\u{10A3F}"\
      "\u{11046}"\
      "\u{11070}"\
      "\u{1107F}"\
      "\u{110B9}"\
      "\u{11133}\u{11134}"\
      "\u{111C0}"\
      "\u{11235}"\
      "\u{112EA}"\
      "\u{1134D}"\
      "\u{11442}"\
      "\u{114C2}"\
      "\u{115BF}"\
      "\u{1163F}"\
      "\u{116B6}"\
      "\u{1172B}"\
      "\u{11839}"\
      "\u{1193D}\u{1193E}"\
      "\u{119E0}"\
      "\u{11A34}"\
      "\u{11A47}"\
      "\u{11A99}"\
      "\u{11C3F}"\
      "\u{11D44}\u{11D45}"\
      "\u{11D97}"\
      "\u{11F41}\u{11F42}"\
      "]"
  end
end
